### ISSUE TITLE
Result mismatch issue

### ISSUE THREAD

**Issue by AsresTemam** [dorothy-yao/drfuse#4]
I have been working with the hyperparameters you provided and applied them to my training process. However, after several runs, I am consistently getting an AUPRC of 0.269 for the partial dataset and 0.361 for the paired dataset. These results are noticeably lower than the reported values in the paper.
Given this, I’m wondering if there might be something I am overlooking or if there are additional details about the setup that I should be aware of. I would greatly appreciate any insights or suggestions you could offer to help me achieve the expected performance.

**Comment by dorothy-yao** [comment]
Hi thanks for your interest in our work. Could you please first check if the data size you extracted from MIMIC-IV is the same as in our paper? Also the version of CUDA and Pytorch and the GPU you are using. Cheers.

**Comment by dorothy-yao** [comment]
Hi thanks for your feedback. We reran the code and the results align with those reported in the paper. We guess the discrepancy is due to different cuda/pytorch versions or GPU models. We have also updated the code to remove some unused arguments for better clarity.  Please feel free to reopen the issue if you have further questions.
